CREATE DATABASE SCHOOL_ST10202790;
USE SCHOOL;
 DROP DATABASE SCHOOL_ST10202790;

CREATE TABLE USERS(
USER_ID INT PRIMARY KEY,
NAME VARCHAR(24),
SURNAME VARCHAR(24),
PASSWORD VARCHAR(200)
);
DROP TABLE MODULES;
SELECT * FROM USERS;
DELETE FROM USERS;

CREATE TABLE MODULES(
MODULE_CODE VARCHAR(24) PRIMARY KEY,
USER_ID INT,
MODULE_NAME VARCHAR(100),
NUMBER_CREDITS INT,
MODULE_HOURS INT,
FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);
CREATE TABLE WORK(
WORK_CODE VARCHAR(24) PRIMARY KEY,
USER_ID INT,
WORK_DATE VARCHAR(24),
WORK_HOURS INT,
FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

SELECT * FROM MODULES;